import 'fish_models.dart';
class FishDefinition {
  final String id;
  final String name;
  final FishRarity rarity;
  final String assetPath;

  const FishDefinition({
    required this.id,
    required this.name,
    required this.rarity,
    required this.assetPath,
  });
}
const List<FishDefinition> fishDefinitions = [
  FishDefinition(
    id: 'esqueleto',
    name: 'Esqueleto',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/esqueleto.png',
  ),
  FishDefinition(
    id: 'submarino',
    name: 'Submarino',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/submarino.png',
  ),
  FishDefinition(
    id: 'fardo',
    name: 'Fardo',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/fardo.png',
  ),
  FishDefinition(
    id: 'muerto',
    name: 'Muerto',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/muerto.png',
  ),
  FishDefinition(
    id: 'nino',
    name: 'Ninez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/nino.png',
  ),
    FishDefinition(
    id: 'alex',
    name: 'alez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/alex.png',
  ),
  FishDefinition(
    id: 'cabegos',
    name: 'cabez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/cabegos.png',
  ),
  FishDefinition(
    id: 'chesco',
    name: 'chez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/chesco.png',
  ),
  FishDefinition(
    id: 'dani',
    name: 'daniez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/dani.png',
  ),
  FishDefinition(
    id: 'enrique',
    name: 'enriquez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/enrique.png',
  ),
    FishDefinition(
    id: 'fede',
    name: 'fedez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/fede.png',
  ),
  FishDefinition(
    id: 'fideo',
    name: 'javieriquez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/fideo.png',
  ),
  FishDefinition(
    id: 'juanma',
    name: 'juanez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/juanma.png',
  ),
  FishDefinition(
    id: 'maiki',
    name: 'miguez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/maiki.png',
  ),
  FishDefinition(
    id: 'montollo',
    name: 'javiez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/montollo.png',
  ),
    FishDefinition(
    id: 'pablo',
    name: 'pablez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/pablo.png',
  ),
  FishDefinition(
    id: 'pedro',
    name: 'pedrez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/pedro.png',
  ),
  FishDefinition(
    id: 'quike',
    name: 'quikez',
    rarity: FishRarity.legendario,
    assetPath: 'lib/assets/legendario/quike.png',
  ),
  FishDefinition(
    id: 'alien',
    name: 'alien',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/alien.png',
  ),
  FishDefinition(
    id: 'caballero',
    name: 'caballero',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/caballero.png',
  ),
  FishDefinition(
    id: 'celestial',
    name: 'celestial',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/celestial.png',
  ),
  FishDefinition(
    id: 'darkclown',
    name: 'it',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/darkclown.png',
  ),
  FishDefinition(
    id: 'fantasma',
    name: 'fantasma',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/fantasma.png',
  ),
  FishDefinition(
    id: 'magikarp',
    name: 'magikarp',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/magikarp.png',
  ),
  FishDefinition(
    id: 'militar',
    name: 'militar',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/militar.png',
  ),
  FishDefinition(
    id: 'ninja',
    name: 'ninja',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/ninja.png',
  ),
  FishDefinition(
    id: 'picoleto',
    name: 'los malos',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/picoleto.png',
  ),
  FishDefinition(
    id: 'pirata',
    name: 'piraton',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/pirata.png',
  ),
  FishDefinition(
    id: 'rey',
    name: 'rey',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/rey.png',
  ),
  FishDefinition(
    id: 'robot',
    name: 'robot',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/robot.png',
  ),
  FishDefinition(
    id: 'rock',
    name: 'kurt pezbein',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/rock.png',
  ),
  FishDefinition(
    id: 'satan',
    name: 'satan',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/satan.png',
  ),
  FishDefinition(
    id: 'vaquero',
    name: 'vaquero',
    rarity: FishRarity.epico,
    assetPath: 'lib/assets/epico/vaquero.png',
  ),
  FishDefinition(
    id: 'abisal',
    name: 'abisal',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/abisal.png',
  ),
  FishDefinition(
    id: 'angel',
    name: 'angel',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/angel.png',
  ),
  FishDefinition(
    id: 'ballena',
    name: 'ballena',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/ballena.png',
  ),
  FishDefinition(
    id: 'caballito',
    name: 'caballito',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/caballito.png',
  ),
  FishDefinition(
    id: 'calamar',
    name: 'calamar',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/calamar.png',
  ),
  FishDefinition(
    id: 'chinata',
    name: 'chino',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/chinata.png',
  ),
    FishDefinition(
    id: 'cofre',
    name: 'cofre',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/cofre.png',
  ),
  FishDefinition(
    id: 'delfin',
    name: 'delfin',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/delfin.png',
  ),
  FishDefinition(
    id: 'demonio',
    name: 'demonio',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/demonio.png',
  ),
  FishDefinition(
    id: 'doncella',
    name: 'doncella',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/doncella.png',
  ),
  FishDefinition(
    id: 'dragon',
    name: 'dragon',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/dragon.png',
  ),
  FishDefinition(
    id: 'espada',
    name: 'espada',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/espada.png',
  ),
    FishDefinition(
    id: 'gamba',
    name: 'gamba',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/gamba.png',
  ),
  FishDefinition(
    id: 'globo',
    name: 'globo',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/globo.png',
  ),
  FishDefinition(
    id: 'lamprea',
    name: 'lamprea',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/lamprea.png',
  ),
  FishDefinition(
    id: 'leon',
    name: 'leon',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/leon.png',
  ),
  FishDefinition(
    id: 'manta',
    name: 'manta',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/manta.png',
  ),
  FishDefinition(
    id: 'martillo',
    name: 'martillo',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/martillo.png',
  ),
    FishDefinition(
    id: 'medusa',
    name: 'medusa',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/medusa.png',
  ),
  FishDefinition(
    id: 'orca',
    name: 'orca',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/orca.png',
  ),
  FishDefinition(
    id: 'payaso',
    name: 'nemo',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/payaso.png',
  ),
  FishDefinition(
    id: 'pulpo',
    name: 'pulpo',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/pulpo.png',
  ),
  FishDefinition(
    id: 'rascasa',
    name: 'rascasa',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/rascasa.png',
  ),
  FishDefinition(
    id: 'tortuga',
    name: 'tortuga',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/tortuga.png',
  ),
  FishDefinition(
    id: 'vibora',
    name: 'vibora',
    rarity: FishRarity.pocoComun,
    assetPath: 'lib/assets/poco comun/vibora.png',
  ),
    FishDefinition(
    id: 'abadejo',
    name: 'abadejo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/abadejo.png',
  ),
      FishDefinition(
    id: 'aguja',
    name: 'aguja',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/aguja.png',
  ),
      FishDefinition(
    id: 'anguila',
    name: 'anguila',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/anguila.png',
  ),
      FishDefinition(
    id: 'arenque',
    name: 'arenque',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/arenque.png',
  ),
      FishDefinition(
    id: 'atun',
    name: 'atun',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/atun.png',
  ),
      FishDefinition(
    id: 'bacalao',
    name: 'bacalao',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/bacalao.png',
  ),
      FishDefinition(
    id: 'barbo',
    name: 'barbo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/barbo.png',
  ),
      FishDefinition(
    id: 'besugo',
    name: 'besugo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/besugo.png',
  ),
      FishDefinition(
    id: 'boga',
    name: 'boga',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/boga.png',
  ),
      FishDefinition(
    id: 'boqueron',
    name: 'boqueron',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/boqueron.png',
  ),
      FishDefinition(
    id: 'breca',
    name: 'breca',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/breca.png',
  ),
      FishDefinition(
    id: 'caballa',
    name: 'caballa',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/caballa.png',
  ),
      FishDefinition(
    id: 'cabrilla',
    name: 'cabrilla',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/cabrilla.png',
  ),
      FishDefinition(
    id: 'carbonero',
    name: 'carbonero',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/carbonero.png',
  ),
        FishDefinition(
    id: 'carpa',
    name: 'carpa',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/carpa.png',
  ),
        FishDefinition(
    id: 'cazon',
    name: 'cazon',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/cazon.png',
  ),
        FishDefinition(
    id: 'congrio',
    name: 'congrio',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/congrio.png',
  ),
        FishDefinition(
    id: 'corvina',
    name: 'corvina',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/corvina.png',
  ),
        FishDefinition(
    id: 'denton',
    name: 'denton',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/denton.png',
  ),
        FishDefinition(
    id: 'dorada',
    name: 'dorada',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/dorada.png',
  ),
        FishDefinition(
    id: 'espeton',
    name: 'espeton',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/espeton.png',
  ),
        FishDefinition(
    id: 'faneca',
    name: 'faneca',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/faneca.png',
  ),
        FishDefinition(
    id: 'gallo',
    name: 'gallo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/gallo.png',
  ),
        FishDefinition(
    id: 'jurel',
    name: 'jurel',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/jurel.png',
  ),
        FishDefinition(
    id: 'lenguado',
    name: 'lenguado',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/lenguado.png',
  ),
        FishDefinition(
    id: 'lisa',
    name: 'lisa',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/lisa.png',
  ),
        FishDefinition(
    id: 'lubina',
    name: 'lubina',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/lubina.png',
  ),
        FishDefinition(
    id: 'lucio',
    name: 'lucio',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/lucio.png',
  ),
        FishDefinition(
    id: 'maragota',
    name: 'maragota',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/maragota.png',
  ),
        FishDefinition(
    id: 'merluza',
    name: 'merluza',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/merluza.png',
  ),
        FishDefinition(
    id: 'mojarra',
    name: 'mojarra',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/mojarra.png',
  ),
        FishDefinition(
    id: 'mujol',
    name: 'mujol',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/mujol.png',
  ),
        FishDefinition(
    id: 'oblada',
    name: 'oblada',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/oblada.png',
  ),
        FishDefinition(
    id: 'pagel',
    name: 'pagel',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/pagel.png',
  ),
        FishDefinition(
    id: 'palometa',
    name: 'palometa',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/palometa.png',
  ),
        FishDefinition(
    id: 'pargo',
    name: 'pargo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/pargo.png',
  ),
        FishDefinition(
    id: 'perca',
    name: 'perca',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/perca.png',
  ),
        FishDefinition(
    id: 'plantilla',
    name: 'pez',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/plantilla.png',
  ),
        FishDefinition(
    id: 'rape',
    name: 'rape',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/rape.png',
  ),
        FishDefinition(
    id: 'roncador',
    name: 'roncador',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/roncador.png',
  ),
        FishDefinition(
    id: 'rubio',
    name: 'rubio',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/rubio.png',
  ),
        FishDefinition(
    id: 'salmon',
    name: 'salmon',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/salmon.png',
  ),
        FishDefinition(
    id: 'sardina',
    name: 'sardina',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/sardina.png',
  ),
        FishDefinition(
    id: 'sargo',
    name: 'sargo',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/sargo.png',
  ),
        FishDefinition(
    id: 'serrano',
    name: 'serrano',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/serrano.png',
  ),
        FishDefinition(
    id: 'tambor',
    name: 'tambor',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/tambor.png',
  ),
        FishDefinition(
    id: 'tenca',
    name: 'tenca',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/tenca.png',
  ),
        FishDefinition(
    id: 'tilapia',
    name: 'tilapia',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/tilapia.png',
  ),
        FishDefinition(
    id: 'trucha',
    name: 'trucha',
    rarity: FishRarity.comun,
    assetPath: 'lib/assets/comun/trucha.png',
  ),
];

FishDefinition getFishDefinitionById(String id) {
  return fishDefinitions.firstWhere(
    (e) => e.id == id,
    orElse: () => fishDefinitions.first,
  );
}