// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFeTuSfmcenYd-1OQD-dz649_HmkkK3M',
    appId: '1:836987084822:web:7a69c1f0907ad47fced537',
    messagingSenderId: '836987084822',
    projectId: 'pebapp-dfc40',
    authDomain: 'pebapp-dfc40.firebaseapp.com',
    storageBucket: 'pebapp-dfc40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM0rNmoIDvxql5vCoJGajUQ-CvH2RRXEQ',
    appId: '1:836987084822:android:88e58dc6e88f289cced537',
    messagingSenderId: '836987084822',
    projectId: 'pebapp-dfc40',
    storageBucket: 'pebapp-dfc40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RTG8QnDmlbFRyILN6wGRlenNi3AQYRY',
    appId: '1:836987084822:ios:d2f49ac8392a3127ced537',
    messagingSenderId: '836987084822',
    projectId: 'pebapp-dfc40',
    storageBucket: 'pebapp-dfc40.firebasestorage.app',
    iosBundleId: 'com.example.peb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RTG8QnDmlbFRyILN6wGRlenNi3AQYRY',
    appId: '1:836987084822:ios:d2f49ac8392a3127ced537',
    messagingSenderId: '836987084822',
    projectId: 'pebapp-dfc40',
    storageBucket: 'pebapp-dfc40.firebasestorage.app',
    iosBundleId: 'com.example.peb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRFeTuSfmcenYd-1OQD-dz649_HmkkK3M',
    appId: '1:836987084822:web:9a7c0ab924c1119bced537',
    messagingSenderId: '836987084822',
    projectId: 'pebapp-dfc40',
    authDomain: 'pebapp-dfc40.firebaseapp.com',
    storageBucket: 'pebapp-dfc40.firebasestorage.app',
  );
}
