import 'package:flutter/material.dart';

import '../models/party_card_models.dart';

class PartyCardCatalog {
  PartyCardCatalog(this.cards);

  final Map<String, PartyCardDefinition> cards;

  PartyCardDefinition? byId(String id) => cards[id];

  static PartyCardCatalog seed() {
    return PartyCardCatalog({
      'char_180º_pablo': const PartyCardDefinition(
        id: 'char_180º_pablo',
        name: '180º Pablo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/180º PABLO.jpg',
        cost: 5,
        baseScore: 3,
        origin: CharacterOrigin.elx,
        characterClass: CharacterClass.biotec,
        tags: [CardTag.male, CardTag.pablohdz],
        effects: [CardEffectDefinition(
          type: CardEffectType.loseScore,
          value: 2,
          targetMode: 'TargetCharacter',
          text: 'menos 2 puntos de fiesta' )],
      ),

'char_admin_cabron': const PartyCardDefinition(
        id: 'char_admin_cabron',
        name: 'Admin Cabron',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ADMIN CABRON.jpg',
        cost: 3,
        baseScore: 2,
        origin: CharacterOrigin.chiringuito,
        characterClass: CharacterClass.biotec,
        tags: [CardTag.male, CardTag.abel],
        effects: [CardEffectDefinition(
          type: CardEffectType.customScript,
          scriptId: 'admin_cabron',
          text: 'robas 1 a un biotec y se lo das a un chiringo' )],
      ),

'char_adrien_sarcozy': const PartyCardDefinition(
        id: 'char_adrien_sarcozy',
        name: 'Adrien Sarcozy',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ADRIEN SARCOZY.jpg',
        cost: 5,
        baseScore: 2,
        origin: CharacterOrigin.sanvi,
        characterClass: CharacterClass.popurri,
        tags: [CardTag.adrian, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.stealCardFromHand,
        targetMode: 'TargetPlayer',
        text:'robas una carta a un rival')],
      ),

'char_ainhoa': const PartyCardDefinition(
        id: 'char_ainhoa',
        name: 'Ainhoa',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/AINHOA.jpg',
        cost: 6,
        baseScore: 3,
        origin: CharacterOrigin.sanvi,
        characterClass: CharacterClass.japenu,
        tags: [CardTag.ainhoa,CardTag.female],
        effects: [CardEffectDefinition(type: CardEffectType.customScript,
        scriptId: 'ainhoa',
        text: 'restas 2 puntos a un jugador o lo adjuntas a un monty y ganas 6 ptos')],
      ),

'char_aka_ñoqui': const PartyCardDefinition(
        id: 'char_aka_ñoqui',
        name: 'Aka Ñoqui',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/AKA ÑOQUI.jpg',
        cost: 5,
        baseScore: 1,
        origin: CharacterOrigin.peb,
        characterClass: CharacterClass.discord,
        tags: [CardTag.javierico, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.startOfRoundIncome,
        text:'si tienes mas de 10 monedas ganas 4 mas por ronda',
        targetMode: 'SelfPlayer')],
      ),

'char_alexander_von_kabegos': const PartyCardDefinition(
        id: 'char_alexander_von_kabegos',
        name: 'Alexander Von Kabegos',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ALEXANDER VON KABEGOS.jpg',
        cost: 6,
        baseScore: 2,
        origin: CharacterOrigin.linkedin,
        characterClass: CharacterClass.bubbles,
        tags: [CardTag.cabegos, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.killCharacter,
        targetMode: 'TargetCharacter')],
      ),

'char_alfonso_vintage': const PartyCardDefinition(
        id: 'char_alfonso_vintage',
        name: 'Alfonso Vintage',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ALFONSO VINTAGE.jpg',
        cost: 5,
        baseScore: 2,
        origin: CharacterOrigin.chiringuito,
        characterClass: CharacterClass.mioclub,
        tags: [CardTag.sito,CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.customScript,
        scriptId: 'alfonso_vintage',
        text: 'Roba 1 punto a cada MioClub'),
        ],
      ),

'char_ana': const PartyCardDefinition(
        id: 'char_ana',
        name: 'Ana',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ANA.jpg',
        cost: 5,
        baseScore: 2,
        origin: CharacterOrigin.norte,
        characterClass: CharacterClass.mioclub,
        tags: [CardTag.ana,CardTag.female],
        effects: [CardEffectDefinition(type: CardEffectType.customScript,
        scriptId: 'ana', text: 'roba 1 punto a todo menos cosis malisis, 2 a biotec')],
      ),

'char_black_fose': const PartyCardDefinition(
        id: 'char_black_fose',
        name: 'Black Fose',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/BLACK FOSE.jpg',
        cost: 0,
        baseScore: 1,
        origin: CharacterOrigin.chiringuito,
        characterClass: CharacterClass.biotec,
        tags: [CardTag.fosetomas, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.loseScore, value: 1, targetMode: 'TargetCharacter', text: 'Insulta a alguien para que pierda 1 punto de fiesta')],
      ),

'char_bodas_y_graduaciones_fose': const PartyCardDefinition(
        id: 'char_bodas_y_graduaciones_fose',
        name: 'Bodas Y Graduaciones Fose',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/BODAS Y GRADUACIONES FOSE.jpg',
        cost: 6,
        baseScore: 3,
        origin: CharacterOrigin.elx,
        characterClass: CharacterClass.teamRocket,
        tags: [CardTag.fosetomas, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.customScript, scriptId: 'bodas_y_comuniones', text: 'te llevas un personaje de la siguiente puja gratis')],
      ),

'char_cabegos': const PartyCardDefinition(
        id: 'char_cabegos',
        name: 'Cabegos',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CABEGOS.jpg',
        cost: 5,
        baseScore: 1,
        origin: CharacterOrigin.sanvi,
        characterClass: CharacterClass.festival,
        tags: [CardTag.cabegos,CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.customScript, scriptId: 'cabegos', text: 'tradeas 1 carta por tres de un rival a su eleccion o 2 que tu elijas a ciegas')],
      ),

'char_cafeinomano': const PartyCardDefinition(
        id: 'char_cafeinomano',
        name: 'Cafeinomano',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CAFEINOMANO.jpg',
        cost: 6,
        baseScore: 2,
        origin: CharacterOrigin.elx,
        characterClass: CharacterClass.cosisMalissimis,
        tags: [CardTag.alfonso, CardTag.male],
        effects: [CardEffectDefinition(type: CardEffectType.gainScore, value: 3, targetMode: 'SelfTarget'), CardEffectDefinition(type: CardEffectType.loseScorelater)],
      ),

'char_carmen': const PartyCardDefinition(
        id: 'char_carmen',
        name: 'Carmen',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CARMEN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_carol_guiri': const PartyCardDefinition(
        id: 'char_carol_guiri',
        name: 'Carol Guiri',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CAROL GUIRI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_carolina': const PartyCardDefinition(
        id: 'char_carolina',
        name: 'Carolina',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CAROLINA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_charly_movidas': const PartyCardDefinition(
        id: 'char_charly_movidas',
        name: 'Charly Movidas',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CHARLY MOVIDAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_charly_paseos': const PartyCardDefinition(
        id: 'char_charly_paseos',
        name: 'Charly Paseos',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CHARLY PASEOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_chef_emilio': const PartyCardDefinition(
        id: 'char_chef_emilio',
        name: 'Chef Emilio',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CHEF EMILIO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_chess_ten1': const PartyCardDefinition(
        id: 'char_chess_ten1',
        name: 'Chess Ten1',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CHESS TEN1.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_conor_mcnuñez': const PartyCardDefinition(
        id: 'char_conor_mcnuñez',
        name: 'Conor Mcnuñez',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CONOR McNUÑEZ.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_cooking_pedro': const PartyCardDefinition(
        id: 'char_cooking_pedro',
        name: 'Cooking Pedro',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/COOKING PEDRO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_corporate_miguel': const PartyCardDefinition(
        id: 'char_corporate_miguel',
        name: 'Corporate Miguel',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CORPORATE MIGUEL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_crossfit_quike': const PartyCardDefinition(
        id: 'char_crossfit_quike',
        name: 'Crossfit Quike',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CROSSFIT QUIKE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_cuvictor': const PartyCardDefinition(
        id: 'char_cuvictor',
        name: 'Cuvictor',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/CUVICTOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_daddy_emilio': const PartyCardDefinition(
        id: 'char_daddy_emilio',
        name: 'Daddy Emilio',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/DADDY EMILIO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_dani_snorlax': const PartyCardDefinition(
        id: 'char_dani_snorlax',
        name: 'Dani Snorlax',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/DANI SNORLAX.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_dini': const PartyCardDefinition(
        id: 'char_dini',
        name: 'Dini',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/DINI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_dj_clement': const PartyCardDefinition(
        id: 'char_dj_clement',
        name: 'Dj Clement',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/DJ CLEMENT.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_dr._antonio': const PartyCardDefinition(
        id: 'char_dr._antonio',
        name: 'Dr. Antonio',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/DR. ANTONIO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_eduardo_fulleda': const PartyCardDefinition(
        id: 'char_eduardo_fulleda',
        name: 'Eduardo Fulleda',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/EDUARDO FULLEDA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_el_arrebato': const PartyCardDefinition(
        id: 'char_el_arrebato',
        name: 'El Arrebato',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/EL ARREBATO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_el_farmaceutico': const PartyCardDefinition(
        id: 'char_el_farmaceutico',
        name: 'El Farmaceutico',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/EL FARMACEUTICO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_elputosuneo': const PartyCardDefinition(
        id: 'char_elputosuneo',
        name: 'Elputosuneo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ELPUTOSUNEO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_enfermero_rodríguez': const PartyCardDefinition(
        id: 'char_enfermero_rodríguez',
        name: 'Enfermero Rodríguez',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ENFERMERO RODRÍGUEZ.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_enude18': const PartyCardDefinition(
        id: 'char_enude18',
        name: 'Enude18',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ENUDE18.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_farruquito_cabot': const PartyCardDefinition(
        id: 'char_farruquito_cabot',
        name: 'Farruquito Cabot',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FARRUQUITO CABOT.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_fede_infojobs': const PartyCardDefinition(
        id: 'char_fede_infojobs',
        name: 'Fede Infojobs',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FEDE INFOJOBS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_fede_numismatico': const PartyCardDefinition(
        id: 'char_fede_numismatico',
        name: 'Fede Numismatico',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FEDE NUMISMATICO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_fedelyn_monroe': const PartyCardDefinition(
        id: 'char_fedelyn_monroe',
        name: 'Fedelyn Monroe',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FEDELYN MONROE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_federico_nenuco': const PartyCardDefinition(
        id: 'char_federico_nenuco',
        name: 'Federico Nenuco',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FEDERICO NENUCO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_fose_tomas': const PartyCardDefinition(
        id: 'char_fose_tomas',
        name: 'Fose Tomas',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FOSE TOMAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_francisco_nadal': const PartyCardDefinition(
        id: 'char_francisco_nadal',
        name: 'Francisco Nadal',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FRANCISCO NADAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_fulleneitor': const PartyCardDefinition(
        id: 'char_fulleneitor',
        name: 'Fulleneitor',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/FULLENEITOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_gema': const PartyCardDefinition(
        id: 'char_gema',
        name: 'Gema',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/GEMA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_gengis_lat': const PartyCardDefinition(
        id: 'char_gengis_lat',
        name: 'Gengis Lat',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/GENGIS LAT.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_grace': const PartyCardDefinition(
        id: 'char_grace',
        name: 'Grace',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/GRACE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_hercules_gallego': const PartyCardDefinition(
        id: 'char_hercules_gallego',
        name: 'Hercules Gallego',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/HERCULES GALLEGO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_il_cocciu': const PartyCardDefinition(
        id: 'char_il_cocciu',
        name: 'Il Cocciu',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/IL COCCIU.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_indira': const PartyCardDefinition(
        id: 'char_indira',
        name: 'Indira',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/INDIRA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_inmarcesible': const PartyCardDefinition(
        id: 'char_inmarcesible',
        name: 'Inmarcesible',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/INMARCESIBLE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_ishowjaviericoo': const PartyCardDefinition(
        id: 'char_ishowjaviericoo',
        name: 'Ishowjaviericoo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ISHOWJAVIERICOO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_iván': const PartyCardDefinition(
        id: 'char_iván',
        name: 'Iván',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/IVÁN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_izquierdo': const PartyCardDefinition(
        id: 'char_izquierdo',
        name: 'Izquierdo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/IZQUIERDO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_jesuqristo': const PartyCardDefinition(
        id: 'char_jesuqristo',
        name: 'Jesuqristo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/JESUQRISTO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_jm_zoom_zoom': const PartyCardDefinition(
        id: 'char_jm_zoom_zoom',
        name: 'Jm Zoom Zoom',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/JM ZOOM ZOOM.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_jm8': const PartyCardDefinition(
        id: 'char_jm8',
        name: 'Jm8',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/JM8.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_juanito_reformed': const PartyCardDefinition(
        id: 'char_juanito_reformed',
        name: 'Juanito Reformed',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/JUANITO REFORMED.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_juanma_bankinter': const PartyCardDefinition(
        id: 'char_juanma_bankinter',
        name: 'Juanma Bankinter',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/JUANMA BANKINTER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_kuzco_de_la_cruz': const PartyCardDefinition(
        id: 'char_kuzco_de_la_cruz',
        name: 'Kuzco De La Cruz',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/KUZCO DE LA CRUZ.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_lator_jr': const PartyCardDefinition(
        id: 'char_lator_jr',
        name: 'Lator Jr',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LATOR JR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_legendaria_abel': const PartyCardDefinition(
        id: 'char_legendaria_abel',
        name: 'Legendaria Abel',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEGENDARIA ABEL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_legendaria_fede': const PartyCardDefinition(
        id: 'char_legendaria_fede',
        name: 'Legendaria Fede',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEGENDARIA FEDE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_legendaria_juanma': const PartyCardDefinition(
        id: 'char_legendaria_juanma',
        name: 'Legendaria Juanma',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEGENDARIA JUANMA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_legendaria_maiki': const PartyCardDefinition(
        id: 'char_legendaria_maiki',
        name: 'Legendaria Maiki',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEGENDARIA MAIKI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_legendaria_pitu': const PartyCardDefinition(
        id: 'char_legendaria_pitu',
        name: 'Legendaria Pitu',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEGENDARIA PITU.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_leyre': const PartyCardDefinition(
        id: 'char_leyre',
        name: 'Leyre',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LEYRE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_ludwig_van_montoy': const PartyCardDefinition(
        id: 'char_ludwig_van_montoy',
        name: 'Ludwig Van Montoy',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/LUDWIG VAN MONTOY.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_maiki_loeb': const PartyCardDefinition(
        id: 'char_maiki_loeb',
        name: 'Maiki Loeb',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MAIKI LOEB.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_mancothetower': const PartyCardDefinition(
        id: 'char_mancothetower',
        name: 'Mancothetower',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MANCOTHETOWER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_marc_abel': const PartyCardDefinition(
        id: 'char_marc_abel',
        name: 'Marc Abel',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MARC ABEL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_marinachula': const PartyCardDefinition(
        id: 'char_marinachula',
        name: 'Marinachula',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MARINACHULA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_marinatopo': const PartyCardDefinition(
        id: 'char_marinatopo',
        name: 'Marinatopo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MARINATOPO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_married_paco': const PartyCardDefinition(
        id: 'char_married_paco',
        name: 'Married Paco',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MARRIED PACO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_minilat': const PartyCardDefinition(
        id: 'char_minilat',
        name: 'Minilat',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MINILAT.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_moni': const PartyCardDefinition(
        id: 'char_moni',
        name: 'Moni',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/MONI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_pablico_efese': const PartyCardDefinition(
        id: 'char_pablico_efese',
        name: 'Pablico Efese',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PABLICO EFESE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_pablo_v1': const PartyCardDefinition(
        id: 'char_pablo_v1',
        name: 'Pablo V1',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PABLO V1.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_pablon_james': const PartyCardDefinition(
        id: 'char_pablon_james',
        name: 'Pablon James',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PABLON JAMES.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_paco_traidor': const PartyCardDefinition(
        id: 'char_paco_traidor',
        name: 'Paco Traidor',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PACO TRAIDOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_palmi': const PartyCardDefinition(
        id: 'char_palmi',
        name: 'Palmi',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PALMI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_pazchuli': const PartyCardDefinition(
        id: 'char_pazchuli',
        name: 'Pazchuli',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PAZCHULI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_pepe_sins': const PartyCardDefinition(
        id: 'char_pepe_sins',
        name: 'Pepe Sins',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PEPE SINS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_perito_tasador': const PartyCardDefinition(
        id: 'char_perito_tasador',
        name: 'Perito Tasador',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PERITO TASADOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_peter_panda': const PartyCardDefinition(
        id: 'char_peter_panda',
        name: 'Peter Panda',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PETER PANDA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_phd_quike': const PartyCardDefinition(
        id: 'char_phd_quike',
        name: 'Phd Quike',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PHD QUIKE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_plabletecs_oficial': const PartyCardDefinition(
        id: 'char_plabletecs_oficial',
        name: 'Plabletecs Oficial',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PLABLETECS OFICIAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_psicomonty': const PartyCardDefinition(
        id: 'char_psicomonty',
        name: 'Psicomonty',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/PSICOMONTY.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_quike_n_roll': const PartyCardDefinition(
        id: 'char_quike_n_roll',
        name: 'Quike N Roll',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/QUIKE N ROLL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_rata_electrica': const PartyCardDefinition(
        id: 'char_rata_electrica',
        name: 'Rata Electrica',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/RATA ELECTRICA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_riquez_maduro': const PartyCardDefinition(
        id: 'char_riquez_maduro',
        name: 'Riquez Maduro',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/RIQUEZ MADURO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_sad_enrique': const PartyCardDefinition(
        id: 'char_sad_enrique',
        name: 'Sad Enrique',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SAD ENRIQUE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_saturnino_d._fuster': const PartyCardDefinition(
        id: 'char_saturnino_d._fuster',
        name: 'Saturnino D. Fuster',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SATURNINO D. FUSTER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_señor_bautista': const PartyCardDefinition(
        id: 'char_señor_bautista',
        name: 'Señor Bautista',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SEÑOR BAUTISTA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_shishaman': const PartyCardDefinition(
        id: 'char_shishaman',
        name: 'Shishaman',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SHISHAMAN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_simba': const PartyCardDefinition(
        id: 'char_simba',
        name: 'Simba',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SIMBA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_sofia': const PartyCardDefinition(
        id: 'char_sofia',
        name: 'Sofia',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SOFIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_soto': const PartyCardDefinition(
        id: 'char_soto',
        name: 'Soto',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SOTO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_ss_edison': const PartyCardDefinition(
        id: 'char_ss_edison',
        name: 'Ss Edison',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/SS EDISON.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_termodinámico_jr': const PartyCardDefinition(
        id: 'char_termodinámico_jr',
        name: 'Termodinámico Jr',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/TERMODINÁMICO JR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_the_ferri': const PartyCardDefinition(
        id: 'char_the_ferri',
        name: 'The Ferri',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/THE FERRI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_the_papi': const PartyCardDefinition(
        id: 'char_the_papi',
        name: 'The Papi',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/THE PAPI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_trainee_alejandro': const PartyCardDefinition(
        id: 'char_trainee_alejandro',
        name: 'Trainee Alejandro',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/TRAINEE ALEJANDRO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_unalicantinomas': const PartyCardDefinition(
        id: 'char_unalicantinomas',
        name: 'Unalicantinomas',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/UNALICANTINOMAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_victor_opositor': const PartyCardDefinition(
        id: 'char_victor_opositor',
        name: 'Victor Opositor',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/VICTOR OPOSITOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_victor_squarepants': const PartyCardDefinition(
        id: 'char_victor_squarepants',
        name: 'Victor Squarepants',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/VICTOR SQUAREPANTS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_vir_pombo': const PartyCardDefinition(
        id: 'char_vir_pombo',
        name: 'Vir Pombo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/VIR POMBO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_virginia': const PartyCardDefinition(
        id: 'char_virginia',
        name: 'Virginia',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/VIRGINIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_xxx_fideo': const PartyCardDefinition(
        id: 'char_xxx_fideo',
        name: 'Xxx Fideo',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/XXX FIDEO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_yuri': const PartyCardDefinition(
        id: 'char_yuri',
        name: 'Yuri',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/YURI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'char_zahira': const PartyCardDefinition(
        id: 'char_zahira',
        name: 'Zahira',
        type: PartyCardType.character,
        imageUrl: 'assets/cards/characters/ZAHIRA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),
      'evt_10_euros_3_copas': const PartyCardDefinition(
        id: 'evt_10_euros_3_copas',
        name: '10 Euros 3 Copas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/10 EUROS 3 COPAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_22_en_22': const PartyCardDefinition(
        id: 'evt_22_en_22',
        name: '22 En 22',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/22 EN 22.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_22': const PartyCardDefinition(
        id: 'evt_22',
        name: '22',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/22.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_40_minutos': const PartyCardDefinition(
        id: 'evt_40_minutos',
        name: '40 Minutos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/40 MINUTOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_a_las_3_se_van': const PartyCardDefinition(
        id: 'evt_a_las_3_se_van',
        name: 'A Las 3 Se Van',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/A LAS 3 SE VAN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_a_tomar_por_culo_mónaco': const PartyCardDefinition(
        id: 'evt_a_tomar_por_culo_mónaco',
        name: 'A Tomar Por Culo Mónaco',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/A TOMAR POR CULO MÓNACO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_absenta_negra': const PartyCardDefinition(
        id: 'evt_absenta_negra',
        name: 'Absenta Negra',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ABSENTA NEGRA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_agua_de_valencia': const PartyCardDefinition(
        id: 'evt_agua_de_valencia',
        name: 'Agua De Valencia',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/AGUA DE VALENCIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_aire_acondicionado': const PartyCardDefinition(
        id: 'evt_aire_acondicionado',
        name: 'Aire Acondicionado',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/AIRE ACONDICIONADO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_akuarela': const PartyCardDefinition(
        id: 'evt_akuarela',
        name: 'Akuarela',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/AKUARELA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_almirante_elixir': const PartyCardDefinition(
        id: 'evt_almirante_elixir',
        name: 'Almirante Elixir',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ALMIRANTE ELIXIR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_antipaellas': const PartyCardDefinition(
        id: 'evt_antipaellas',
        name: 'Antipaellas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ANTIPAELLAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_arenal_sound': const PartyCardDefinition(
        id: 'evt_arenal_sound',
        name: 'Arenal Sound',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ARENAL SOUND.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_asado_argentino': const PartyCardDefinition(
        id: 'evt_asado_argentino',
        name: 'Asado Argentino',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ASADO ARGENTINO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_asiatico': const PartyCardDefinition(
        id: 'evt_asiatico',
        name: 'Asiatico',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ASIATICO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_backstage': const PartyCardDefinition(
        id: 'evt_backstage',
        name: 'Backstage',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BACKSTAGE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_barceló': const PartyCardDefinition(
        id: 'evt_barceló',
        name: 'Barceló',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BARCELÓ.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_barracas': const PartyCardDefinition(
        id: 'evt_barracas',
        name: 'Barracas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BARRACAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_bathroom': const PartyCardDefinition(
        id: 'evt_bathroom',
        name: 'Bathroom',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BATHROOM.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_blumara_15': const PartyCardDefinition(
        id: 'evt_blumara_15',
        name: 'Blumara 15',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BLUMARA 15.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_bombeo_prefiesta': const PartyCardDefinition(
        id: 'evt_bombeo_prefiesta',
        name: 'Bombeo Prefiesta',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BOMBEO PREFIESTA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_borrachos': const PartyCardDefinition(
        id: 'evt_borrachos',
        name: 'Borrachos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/BORRACHOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_café_cerol': const PartyCardDefinition(
        id: 'evt_café_cerol',
        name: 'Café Cerol',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CAFÉ CEROL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_calimocho_fermentado': const PartyCardDefinition(
        id: 'evt_calimocho_fermentado',
        name: 'Calimocho Fermentado',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CALIMOCHO FERMENTADO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_campo_fose': const PartyCardDefinition(
        id: 'evt_campo_fose',
        name: 'Campo Fose',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CAMPO FOSE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_campo_tefun': const PartyCardDefinition(
        id: 'evt_campo_tefun',
        name: 'Campo Tefun',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CAMPO TEFUN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_candado_ilicitano': const PartyCardDefinition(
        id: 'evt_candado_ilicitano',
        name: 'Candado Ilicitano',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CANDADO ILICITANO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_carrera_de_caballos': const PartyCardDefinition(
        id: 'evt_carrera_de_caballos',
        name: 'Carrera De Caballos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CARRERA DE CABALLOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_cason_histórico': const PartyCardDefinition(
        id: 'evt_cason_histórico',
        name: 'Cason Histórico',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CASON HISTÓRICO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_casper': const PartyCardDefinition(
        id: 'evt_casper',
        name: 'Casper',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CASPER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_cena_familiar': const PartyCardDefinition(
        id: 'evt_cena_familiar',
        name: 'Cena Familiar',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CENA FAMILIAR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_chupitos_gratis': const PartyCardDefinition(
        id: 'evt_chupitos_gratis',
        name: 'Chupitos Gratis',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CHUPITOS GRATIS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_cierre_del_paraiso': const PartyCardDefinition(
        id: 'evt_cierre_del_paraiso',
        name: 'Cierre Del Paraiso',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CIERRE DEL PARAISO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_cirrosis': const PartyCardDefinition(
        id: 'evt_cirrosis',
        name: 'Cirrosis',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CIRROSIS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_claro_manin': const PartyCardDefinition(
        id: 'evt_claro_manin',
        name: 'Claro Manin',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CLARO MANIN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_clase_del_turreico': const PartyCardDefinition(
        id: 'evt_clase_del_turreico',
        name: 'Clase Del Turreico',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CLASE DEL TURREICO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_clausulazo': const PartyCardDefinition(
        id: 'evt_clausulazo',
        name: 'Clausulazo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CLAUSULAZO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_clean_bubbles': const PartyCardDefinition(
        id: 'evt_clean_bubbles',
        name: 'Clean Bubbles',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CLEAN BUBBLES.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_coche_invisible': const PartyCardDefinition(
        id: 'evt_coche_invisible',
        name: 'Coche Invisible',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/COCHE INVISIBLE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_cojonazos_parera': const PartyCardDefinition(
        id: 'evt_cojonazos_parera',
        name: 'Cojonazos Parera',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/COJONAZOS PARERA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_comedia_en_navidad': const PartyCardDefinition(
        id: 'evt_comedia_en_navidad',
        name: 'Comedia En Navidad',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/COMEDIA EN NAVIDAD.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_comisiones_inmuno': const PartyCardDefinition(
        id: 'evt_comisiones_inmuno',
        name: 'Comisiones Inmuno',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/COMISIONES INMUNO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_compra_compartida': const PartyCardDefinition(
        id: 'evt_compra_compartida',
        name: 'Compra Compartida',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/COMPRA COMPARTIDA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_crossover_definitivo': const PartyCardDefinition(
        id: 'evt_crossover_definitivo',
        name: 'Crossover Definitivo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/CROSSOVER DEFINITIVO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_daytona': const PartyCardDefinition(
        id: 'evt_daytona',
        name: 'Daytona',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/DAYTONA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_dreambeach': const PartyCardDefinition(
        id: 'evt_dreambeach',
        name: 'Dreambeach',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/DREAMBEACH.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_duro_como_un_olivo': const PartyCardDefinition(
        id: 'evt_duro_como_un_olivo',
        name: 'Duro Como Un Olivo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/DURO COMO UN OLIVO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_echame_el_humo': const PartyCardDefinition(
        id: 'evt_echame_el_humo',
        name: 'Echame El Humo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ECHAME EL HUMO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_el_escondite': const PartyCardDefinition(
        id: 'evt_el_escondite',
        name: 'El Escondite',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/EL ESCONDITE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_el_patrocinador': const PartyCardDefinition(
        id: 'evt_el_patrocinador',
        name: 'El Patrocinador',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/EL PATROCINADOR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_el_veto': const PartyCardDefinition(
        id: 'evt_el_veto',
        name: 'El Veto',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/EL VETO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_encontró_trabajo': const PartyCardDefinition(
        id: 'evt_encontró_trabajo',
        name: 'Encontró Trabajo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ENCONTRÓ TRABAJO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_escala_de_rayazos': const PartyCardDefinition(
        id: 'evt_escala_de_rayazos',
        name: 'Escala De Rayazos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ESCALA DE RAYAZOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_escala_del_juaneo': const PartyCardDefinition(
        id: 'evt_escala_del_juaneo',
        name: 'Escala Del Juaneo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ESCALA DEL JUANEO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_esta_noche_carricoche': const PartyCardDefinition(
        id: 'evt_esta_noche_carricoche',
        name: 'Esta Noche Carricoche',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ESTA NOCHE CARRICOCHE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_eurotúnel': const PartyCardDefinition(
        id: 'evt_eurotúnel',
        name: 'Eurotúnel',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/EUROTÚNEL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_examen_ambiental': const PartyCardDefinition(
        id: 'evt_examen_ambiental',
        name: 'Examen Ambiental',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/EXAMEN AMBIENTAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fallas': const PartyCardDefinition(
        id: 'evt_fallas',
        name: 'Fallas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FALLAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_falsa_promesa': const PartyCardDefinition(
        id: 'evt_falsa_promesa',
        name: 'Falsa Promesa',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FALSA PROMESA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_feliz_año': const PartyCardDefinition(
        id: 'evt_feliz_año',
        name: 'Feliz Año',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FELIZ AÑO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fernando_alonso': const PartyCardDefinition(
        id: 'evt_fernando_alonso',
        name: 'Fernando Alonso',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FERNANDO ALONSO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fiesta_en_la_tundra': const PartyCardDefinition(
        id: 'evt_fiesta_en_la_tundra',
        name: 'Fiesta En La Tundra',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FIESTA EN LA TUNDRA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fiestasbiotecnología': const PartyCardDefinition(
        id: 'evt_fiestasbiotecnología',
        name: 'Fiestasbiotecnología',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FIESTASBIOTECNOLOGÍA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fiestwitter': const PartyCardDefinition(
        id: 'evt_fiestwitter',
        name: 'Fiestwitter',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FIESTWITTER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_foto_letal': const PartyCardDefinition(
        id: 'evt_foto_letal',
        name: 'Foto Letal',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FOTO LETAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_foto_protocolaria': const PartyCardDefinition(
        id: 'evt_foto_protocolaria',
        name: 'Foto Protocolaria',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FOTO PROTOCOLARIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_funeral': const PartyCardDefinition(
        id: 'evt_funeral',
        name: 'Funeral',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FUNERAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_fusil_verde': const PartyCardDefinition(
        id: 'evt_fusil_verde',
        name: 'Fusil Verde',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/FUSIL VERDE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_gafas_de_llorar': const PartyCardDefinition(
        id: 'evt_gafas_de_llorar',
        name: 'Gafas De Llorar',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/GAFAS DE LLORAR.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_gluten': const PartyCardDefinition(
        id: 'evt_gluten',
        name: 'Gluten',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/GLUTEN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_guarida_del_lobo': const PartyCardDefinition(
        id: 'evt_guarida_del_lobo',
        name: 'Guarida Del Lobo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/GUARIDA DEL LOBO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_halo': const PartyCardDefinition(
        id: 'evt_halo',
        name: 'Halo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/HALO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_hogueras': const PartyCardDefinition(
        id: 'evt_hogueras',
        name: 'Hogueras',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/HOGUERAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_jijantes_fc': const PartyCardDefinition(
        id: 'evt_jijantes_fc',
        name: 'Jijantes Fc',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/JIJANTES FC.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_joder_que_rubia': const PartyCardDefinition(
        id: 'evt_joder_que_rubia',
        name: 'Joder Que Rubia',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/JODER QUE RUBIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_king_mortadelo': const PartyCardDefinition(
        id: 'evt_king_mortadelo',
        name: 'King Mortadelo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/KING MORTADELO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_knebep': const PartyCardDefinition(
        id: 'evt_knebep',
        name: 'Knebep',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/KNEBEP.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_korner': const PartyCardDefinition(
        id: 'evt_korner',
        name: 'Korner',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/KORNER.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_la_noche_de_la_cebolla': const PartyCardDefinition(
        id: 'evt_la_noche_de_la_cebolla',
        name: 'La Noche De La Cebolla',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LA NOCHE DE LA CEBOLLA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_la_piramide': const PartyCardDefinition(
        id: 'evt_la_piramide',
        name: 'La Piramide',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LA PIRAMIDE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_la_sede': const PartyCardDefinition(
        id: 'evt_la_sede',
        name: 'La Sede',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LA SEDE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_la_tradició_del_mitja': const PartyCardDefinition(
        id: 'evt_la_tradició_del_mitja',
        name: 'La Tradició Del Mitja',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LA TRADICIÓ DEL MITJA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_leo_season_baby': const PartyCardDefinition(
        id: 'evt_leo_season_baby',
        name: 'Leo Season Baby',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LEO SEASON BABY.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_licor_chino': const PartyCardDefinition(
        id: 'evt_licor_chino',
        name: 'Licor Chino',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LICOR CHINO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_licor_de_hierbas': const PartyCardDefinition(
        id: 'evt_licor_de_hierbas',
        name: 'Licor De Hierbas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/LICOR DE HIERBAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_mad_pilots': const PartyCardDefinition(
        id: 'evt_mad_pilots',
        name: 'Mad Pilots',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MAD PILOTS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_mae_west': const PartyCardDefinition(
        id: 'evt_mae_west',
        name: 'Mae West',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MAE WEST.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_malibu_piña': const PartyCardDefinition(
        id: 'evt_malibu_piña',
        name: 'Malibu Piña',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MALIBU PIÑA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_marmarela': const PartyCardDefinition(
        id: 'evt_marmarela',
        name: 'Marmarela',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MARMARELA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_megamix_rio': const PartyCardDefinition(
        id: 'evt_megamix_rio',
        name: 'Megamix Rio',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MEGAMIX RIO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_mejor_disco_de_rap': const PartyCardDefinition(
        id: 'evt_mejor_disco_de_rap',
        name: 'Mejor Disco De Rap',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MEJOR DISCO DE RAP.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_meloncello': const PartyCardDefinition(
        id: 'evt_meloncello',
        name: 'Meloncello',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MELONCELLO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_mio_club': const PartyCardDefinition(
        id: 'evt_mio_club',
        name: 'Mio Club',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/MIO CLUB.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_no_está_lloviendo': const PartyCardDefinition(
        id: 'evt_no_está_lloviendo',
        name: 'No Está Lloviendo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/NO ESTÁ LLOVIENDO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_no_me_cuentes_monsergas': const PartyCardDefinition(
        id: 'evt_no_me_cuentes_monsergas',
        name: 'No Me Cuentes Monsergas',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/NO ME CUENTES MONSERGAS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_ombu': const PartyCardDefinition(
        id: 'evt_ombu',
        name: 'Ombu',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/OMBU.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_pacto_de_beijing': const PartyCardDefinition(
        id: 'evt_pacto_de_beijing',
        name: 'Pacto De Beijing',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PACTO DE BEIJING.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_paellas_umh': const PartyCardDefinition(
        id: 'evt_paellas_umh',
        name: 'Paellas Umh',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PAELLAS UMH.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_palo_estepario': const PartyCardDefinition(
        id: 'evt_palo_estepario',
        name: 'Palo Estepario',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PALO ESTEPARIO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_parole': const PartyCardDefinition(
        id: 'evt_parole',
        name: 'Parole',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PAROLE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_phoenix_dactilifera': const PartyCardDefinition(
        id: 'evt_phoenix_dactilifera',
        name: 'Phoenix Dactilifera',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PHOENIX DACTILIFERA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_piscina_casa_rural': const PartyCardDefinition(
        id: 'evt_piscina_casa_rural',
        name: 'Piscina Casa Rural',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PISCINA CASA RURAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_podmania': const PartyCardDefinition(
        id: 'evt_podmania',
        name: 'Podmania',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/PODMANIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_que': const PartyCardDefinition(
        id: 'evt_que',
        name: 'Que',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/QUE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_quid_pro_quo': const PartyCardDefinition(
        id: 'evt_quid_pro_quo',
        name: 'Quid Pro Quo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/QUID PRO QUO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_rabolagartija': const PartyCardDefinition(
        id: 'evt_rabolagartija',
        name: 'Rabolagartija',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RABOLAGARTIJA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_rascacielos': const PartyCardDefinition(
        id: 'evt_rascacielos',
        name: 'Rascacielos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RASCACIELOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_remember_reggaeton': const PartyCardDefinition(
        id: 'evt_remember_reggaeton',
        name: 'Remember Reggaeton',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/REMEMBER REGGAETON.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_remontada_concerto': const PartyCardDefinition(
        id: 'evt_remontada_concerto',
        name: 'Remontada Concerto',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/REMONTADA CONCERTO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_resi': const PartyCardDefinition(
        id: 'evt_resi',
        name: 'Resi',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RESI.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_rojales': const PartyCardDefinition(
        id: 'evt_rojales',
        name: 'Rojales',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ROJALES.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_rojo_par_y_pasa': const PartyCardDefinition(
        id: 'evt_rojo_par_y_pasa',
        name: 'Rojo Par Y Pasa',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/ROJO PAR Y PASA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_ron_almirante': const PartyCardDefinition(
        id: 'evt_ron_almirante',
        name: 'Ron Almirante',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RON ALMIRANTE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_ron': const PartyCardDefinition(
        id: 'evt_ron',
        name: 'Ron',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RON.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_ruzafa': const PartyCardDefinition(
        id: 'evt_ruzafa',
        name: 'Ruzafa',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/RUZAFA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_salimos_por_alicante': const PartyCardDefinition(
        id: 'evt_salimos_por_alicante',
        name: 'Salimos Por Alicante',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SALIMOS POR ALICANTE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_selección_argelina': const PartyCardDefinition(
        id: 'evt_selección_argelina',
        name: 'Selección Argelina',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SELECCIÓN ARGELINA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_servers_caídos': const PartyCardDefinition(
        id: 'evt_servers_caídos',
        name: 'Servers Caídos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SERVERS CAÍDOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_si_vuelcas_tú,_vuelco_yo': const PartyCardDefinition(
        id: 'evt_si_vuelcas_tú,_vuelco_yo',
        name: 'Si Vuelcas Tú, Vuelco Yo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SI VUELCAS TÚ, VUELCO YO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_sidra_de_regalo': const PartyCardDefinition(
        id: 'evt_sidra_de_regalo',
        name: 'Sidra De Regalo',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SIDRA DE REGALO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_soy_100tifiko': const PartyCardDefinition(
        id: 'evt_soy_100tifiko',
        name: 'Soy 100tifiko',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SOY 100TIFIKO.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_stroh': const PartyCardDefinition(
        id: 'evt_stroh',
        name: 'Stroh',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/STROH.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_sunset_party': const PartyCardDefinition(
        id: 'evt_sunset_party',
        name: 'Sunset Party',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/SUNSET PARTY.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_tackle_a_la_tibia': const PartyCardDefinition(
        id: 'evt_tackle_a_la_tibia',
        name: 'Tackle A La Tibia',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/TACKLE A LA TIBIA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_tequila': const PartyCardDefinition(
        id: 'evt_tequila',
        name: 'Tequila',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/TEQUILA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_the_one': const PartyCardDefinition(
        id: 'evt_the_one',
        name: 'The One',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/THE ONE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_the_stepcousin': const PartyCardDefinition(
        id: 'evt_the_stepcousin',
        name: 'The Stepcousin',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/THE STEPCOUSIN.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_three_kingdoms': const PartyCardDefinition(
        id: 'evt_three_kingdoms',
        name: 'Three Kingdoms',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/THREE KINGDOMS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_treasure': const PartyCardDefinition(
        id: 'evt_treasure',
        name: 'Treasure',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/TREASURE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_truco_stinson': const PartyCardDefinition(
        id: 'evt_truco_stinson',
        name: 'Truco Stinson',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/TRUCO STINSON.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_turra_demencial': const PartyCardDefinition(
        id: 'evt_turra_demencial',
        name: 'Turra Demencial',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/TURRA DEMENCIAL.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_una_mala_y_nos_vamos': const PartyCardDefinition(
        id: 'evt_una_mala_y_nos_vamos',
        name: 'Una Mala Y Nos Vamos',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/UNA MALA Y NOS VAMOS.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_via_picc': const PartyCardDefinition(
        id: 'evt_via_picc',
        name: 'Via Picc',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/VIA PICC.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_vine_vine': const PartyCardDefinition(
        id: 'evt_vine_vine',
        name: 'Vine Vine',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/VINE VINE.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_viñarock': const PartyCardDefinition(
        id: 'evt_viñarock',
        name: 'Viñarock',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/VIÑAROCK.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_waka': const PartyCardDefinition(
        id: 'evt_waka',
        name: 'Waka',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/WAKA.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),

'evt_whisky': const PartyCardDefinition(
        id: 'evt_whisky',
        name: 'Whisky',
        type: PartyCardType.event,
        imageUrl: 'assets/cards/events/WHISKY.jpg',
        cost: 0,
        baseScore: 0,
        origin: null,
        characterClass: null,
        tags: [],
        effects: [],
      ),
    });
  }
}